const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..", "..");

module.exports = {
  projectRoot,
  launcherRoot: path.join(projectRoot, "launcher"),
  toolsRoot: path.join(projectRoot, "tools"),
  catalogDir: path.join(projectRoot, "catalog"),
  runtimeDataDir: path.join(projectRoot, "runtime-data"),
  userAudioDir: path.join(projectRoot, "runtime-data", "user-audio"),
  qaDir: path.join(projectRoot, "runtime-data", "qa"),
  superPowerQaDir: path.join(projectRoot, "runtime-data", "qa", "super-power"),
  patchedZipsDir: path.join(projectRoot, "runtime-data", "patched-zips"),
  nativeToolsDir: path.join(projectRoot, "runtime-data", "native-tools"),
  workspacesDir: path.join(projectRoot, "runtime-data", "workspaces"),
  managedWorkspaceDir: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed"),
  managedServiceRootDir: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-service-root"),
  packsDir: path.join(projectRoot, "packs"),
  zhCnPackDir: path.join(projectRoot, "packs", "zh-CN"),
  as2PackDir: path.join(projectRoot, "packs", "zh-CN", "as2"),
  as3PackDir: path.join(projectRoot, "packs", "zh-CN", "as3"),
  configPath: path.join(projectRoot, "runtime-data", "user-config.json"),
  textIndexPath: path.join(projectRoot, "runtime-data", "text-index.sqlite"),
  coverageMatrixPath: path.join(projectRoot, "catalog", "coverage-matrix.json"),
  islandsPath: path.join(projectRoot, "catalog", "islands.json"),
  islandNamesPath: path.join(projectRoot, "catalog", "island-names.zh-CN.json"),
  launchManifestPath: path.join(projectRoot, "catalog", "launch-manifest.json"),
  launchOverridesPath: path.join(projectRoot, "catalog", "launch-overrides.json"),
  missesPath: path.join(projectRoot, "runtime-data", "misses.jsonl"),
  seenAssetsPath: path.join(projectRoot, "runtime-data", "seen-assets.jsonl"),
  extractedDir: path.join(projectRoot, "runtime-data", "extracted"),
  tempDir: path.join(projectRoot, "runtime-data", "tmp"),
  packMetaPath: path.join(projectRoot, "runtime-data", "pack-meta.json"),
  e2eQuickReportPath: path.join(projectRoot, "runtime-data", "e2e-quick-report.json"),
  as2RuntimeZipPath: path.join(projectRoot, "runtime-data", "patched-zips", "as2-runtime.zip"),
  as3RuntimeZipPath: path.join(projectRoot, "runtime-data", "patched-zips", "as3-runtime.zip"),
  as3RuntimeStartFlowZipPath: path.join(projectRoot, "runtime-data", "patched-zips", "as3-runtime-startflow.zip"),
  flashpointRuntimeStatePath: path.join(projectRoot, "runtime-data", "flashpoint-runtime-state.json"),
  doctorReportPath: path.join(projectRoot, "runtime-data", "doctor-flashpoint.json"),
  lastLaunchPlanPath: path.join(projectRoot, "runtime-data", "last-launch-plan.json"),
  islandVerificationPath: path.join(projectRoot, "runtime-data", "island-verification.json"),
  playerCompatibilityPath: path.join(projectRoot, "runtime-data", "player-compatibility.json"),
  windowAuditPath: path.join(projectRoot, "runtime-data", "window-audit.json"),
  managedDbPath: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "flashpoint.sqlite"),
  managedPreferencesPath: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "preferences.json"),
  managedExtConfigPath: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "extConfig.json"),
  managedLogsDir: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "logs"),
  managedLibraryPath: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "poptropica-library.json"),
  managedServiceMetaPath: path.join(projectRoot, "runtime-data", "workspaces", "flashpoint-managed", "service-root.json"),
  phpCgiWrapperProjectDir: path.join(projectRoot, "tools", "native", "php-cgi-wrapper"),
  phpCgiWrapperPublishDir: path.join(projectRoot, "runtime-data", "native-tools", "php-cgi-wrapper"),
  rootEnvPath: path.resolve(projectRoot, "..", ".env.local"),
  localEnvPath: path.join(projectRoot, ".env.local")
};
